name: Docker Image CI

on: 
  workflow_dispatch:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --build-arg TAG=release -t jkwmoore/chaste-docker:release .
      
    - name: Run tests
      run: docker run jkwmoore/chaste:release bash -c 'cd $CHASTE_BUILD_DIR && ctest -j$(nproc) -L Continuous'
