name: Docker Image CI

on: 
  workflow_dispatch:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --build-arg TAG=release -t jkwmoore/chaste-docker:release .
      
    - name: Run Docker tests
      run: docker run jkwmoore/chaste:release bash -c 'cd $CHASTE_BUILD_DIR && ctest -j$(nproc) -L Continuous'

    - name: Run Singularity tests
      run: singularity exec docker://ubuntu:18.04 bash -c 'mkdir -p overlay_tmp/upper overlay_tmp/work && dd if=/dev/zero of=my_overlay count=1000 bs=1M && mkfs.ext3 -d overlay_tmp my_overlay && rm -rf overlay_tmp' && singularity run --overlay my_overlay docker://jkwmoore/chaste-docker:release bash -c  'cd $CHASTE_BUILD_DIR && ctest -j$(nproc) -L Continuous' ; rm my_overlay

